khushi-purwar/WebDev-ProjectKart

15.Weather_Application/Assets/css/style.css
<hr>
Project name
(Weather Application)
Improvements done 
(used media queries for different devices and made it responsive and super clean)
Happy coding!
Fixes #35 
<hr>
<hr>
<hr>
<hr>
=> issue #35  weather application not responsive

25. Curruncy Converter/Readme.md, 25. Curruncy Converter/function.js, 25. Curruncy Converter/index.html, 25. Curruncy Converter/style.css
=> currency converter

Quiz App/Js/index.js, Quiz App/README.md, Quiz App/index.html, Quiz App/styles/index.css
<hr>
(It is a very simple quiz type game where it will be a question and there will be 4 multiple options for the user to select the answer if the answer will be correct then the user can be able to go on to the next question, for now, it has only four questions but the user can add their own questions and answers to the project🙂)
Fixes #<49>
<hr>
Please delete options that are not relevant. And in order to tick the check box just but x inside them for example [x] like this
<hr>
Please delete options that are not relevant. And in order to tick the check box just but x inside them for example [x] like this
<hr>
Please delete options that are not relevant. And in order to tick the check box just but x inside them for example [x] like this
<hr>
=> Added Quiz Game app to The WebDev-ProjectKart Repository

Color Flipper/index.html, Color Flipper/sond.js, Color Flipper/sondi.css
<hr>
When User clicks on the button, it flips the background Color
Fixes #85 
<hr>
<hr>
<hr>
<hr>
=> Added Color Flipper

LoginForm/.gitignore, LoginForm/index.html, LoginForm/package-lock.json, LoginForm/script.js, LoginForm/style.css
<hr>
Add a Login form with captcha feature .
Fixes #127 
<hr>
<hr>
<hr>
<hr>
=>  Added Login form with captcha feature

21.Random_grediant_color/assets/css/style.css, 21.Random_grediant_color/index.html, 21.Random_grediant_color/script/index.js
<hr>
Fixes #33
<hr>
- [ x] Modified or enhanced the existing projects
- [ x] Added copy button for copy the gradient  
<hr>
- [x ] Project using only HTML & CSS
- [ x] Project using HTML, CSS & JS
<hr>
Please delete options that are not relevant. And in order to tick the check box just but x inside them for example [x] like this
<hr>
=> Code enhance in Random gradient color

01.Password_Generator/Assets/css/style.css, 01.Password_Generator/index.html
<hr>
Fixes #67 
I did not add integer dropdown as I mentioned in the issue because it was making for a bad user experience.
<hr>
<hr>
<hr>
<hr>
=> Fixes issue #67

style.css
<hr>
I am added following hover effects:
- background color change to #808080
- enlargement of background
- text color change to white
Fixes #140 
<hr>
<hr>
<hr>
<hr>
=> Hover effect

README.md
<hr>
Fix a grammatical error in the readme file  
Issue : #45 
<hr>
- [:white_check_mark: ] Improve the readme of any project
<hr>
=> [Bugfixed] Readme.md

34.Maze-Game/css/style.css, 34.Maze-Game/index.html, 34.Maze-Game/js/index.js, index.html
<hr>
Added Maze Game Project.
Fixes #175 
The maze game works by presenting a maze in front of the user with a caterpillar that would like to feed on the cabbage but has to reach it through a maze. **The player has to navigate the caterpillar using the arrow buttons of the keyboard or using the mouse and help it reach the cabbage**. It **also works on phone screens perfectly** and the user can select the caterpillar and send it to desired location using hand touch. This game also has option to select from **various difficulty levels viz : Easy, Medium, Hard and Extreme** and with each increasing level, the user is presented with a more complex maze. Every single maze is different and unique.
<hr>
<hr>
Please delete options that are not relevant.And in order to tick the check box just but …
=> Added Maze Game Project

18.Stopwatch_App/Assets/css/style.css, 18.Stopwatch_App/index.html, 18.Stopwatch_App/script/script.js
<hr>
improve the styling of the stopwatch and add lap in stopwatch
Fixes #138
<hr>
- [✅] Improve the readme of any project
<hr>
- [✅] Project using HTML, CSS & JS
<hr>
- [✅ ] I'm GSSoC'22 contributor
<hr>
Previous style Screenshot
That Time looks of Stopwatch
=> improve stopwatch

Neumorphic-power-button/README.md, Neumorphic-power-button/index.html, Neumorphic-power-button/style.css
<hr>
Creating new project
Fixes #145 
<hr>
- [✅] Add a new project
<hr>
- [✅ ] Project using only HTML & CSS
<hr>
- [✅] I'm GSSoC'22 contributor
<hr>
=> Neumorphic  power button 

GitHub Profiles/README.md, GitHub Profiles/index.html, GitHub Profiles/script.js, GitHub Profiles/style.css
<hr>
Added a new project which is to get the user information from GitHub including description, repo names, followers, followings and other details.
Fixes #218 
<hr>
<hr>
<hr>
<hr>
**Example 1**
**Example 2**
**Example 3**
=> GitHub profile project 218

CRUD_Project/README.md, CRUD_Project/assets/style.css, CRUD_Project/index.html, CRUD_Project/script/script.js
CRUD Project
Fixes #194
<hr>
<hr>
<hr>
=> Added CRUD PROJECT 

18.Stopwatch_App/Assets/css/style.css, 18.Stopwatch_App/index.html, 18.Stopwatch_App/script/script.js
[](url)<hr>
I improved the HTML, CSS and JS files . There was a small bug in that clear button I fixed that . I changed the background and the box designs now it looks good . The buttons where too small so I changed that too.
Fixes #228 
<hr>
<hr>
<hr>
<hr>
=> Improved UI of Stopwatch app

Tic-Tac-Toe-Multiplayer/package-lock.json, Tic-Tac-Toe-Multiplayer/package.json, Tic-Tac-Toe-Multiplayer/public/css/index.css, Tic-Tac-Toe-Multiplayer/public/css/room.css, Tic-Tac-Toe-Multiplayer/public/js/index.js, Tic-Tac-Toe-Multiplayer/public/js/room.js, Tic-Tac-Toe-Multiplayer/server.js, Tic-Tac-Toe-Multiplayer/views/index.ejs, Tic-Tac-Toe-Multiplayer/views/room.ejs
<hr>
Fixes #226
<hr>
<hr>
<hr>
<hr>
=> Add tic tac toe online multiplayer

Customize-Ice-Cream/index.html, Customize-Ice-Cream/script.js, Customize-Ice-Cream/styles.css, index.html
<hr>
Fixes #55 
<hr>
<hr>
<hr>
<hr>
=> Custom Ice cream files added

09.Quote_Generator/Assets/css/style.css, 09.Quote_Generator/index.html
<hr>
I have improved the background ,Font and font-style, color etc..
Fixes #215 
<hr>
<hr>
<hr>
<hr>
(Before)-
(After)-
=> Changes done according to the issue raised.

ModelWindow/.prettierrc, ModelWindow/index.html, ModelWindow/script.js, ModelWindow/style.css
issue no.  #249
https://user-images.githubusercontent.com/93531189/157371851-65aa0602-36e3-4cd7-b73e-c83710157240.mp4
=> Model Window

RD return calculator/index.html, RD return calculator/readme.md, RD return calculator/script.js, RD return calculator/style.css
<hr>
Project Name : RD return calculator
The RD(recurring deposit) calculator calculates and displays the total invested amount, total estimated return and total maturity amount.
The user needs to enter the monthly deposit amount, rate of interest and the year.
Fixes #271 
<hr>
<hr>
<hr>
<hr>
=> Rd calculator

37.Palindrome_Checker/README.md, 37.Palindrome_Checker/index.html, 37.Palindrome_Checker/script.js, 37.Palindrome_Checker/style.css, index.html
<hr>
Added Palindrome Checker Project which contain the following files :
- README.md
- index.html
- style.css
- script.js 
Fixes #170 
<hr>
<hr>
<hr>
<hr>
=> Palindrome checker

08.Calculator/Assets/css/style.css, 08.Calculator/index.html, 08.Calculator/script/script.js
<hr>
I have added a button by which user can switch from light/dark theme.
I have made changes from line 155-168 in style.css ,line 84-87 in script.js and 12-14 in index.html. rest of the code is not changed.
Kindly review it.
Fixes #149
<hr>
<hr>
<hr>
<hr>
=> branch_first

Youtube-Video-Downloader-App/app.js, Youtube-Video-Downloader-App/package-lock.json, Youtube-Video-Downloader-App/package.json, Youtube-Video-Downloader-App/public/index.css, Youtube-Video-Downloader-App/public/index.html, Youtube-Video-Downloader-App/public/index.js
<hr>
Create a youtube video downloader and pushing it to this collection of projects.
Fixes #245
<hr>
<hr>
<hr>
<hr>
=> Create YouTube Video Downloader

Sample Product Landing Page/Assets/css/index.css, Sample Product Landing Page/index.html, Sample Product Landing Page/readme.md
<hr>
Added a small web development project on product landing page for gardening products
Fixes #295 
<hr>
<hr>
<hr>
<hr>
https://user-images.githubusercontent.com/80174214/158063879-fefe5965-6894-41c0-ac44-568544344add.mp4
=> Added Sample Product Landing Page

ping-pong game/ball.js, ping-pong game/index.html, ping-pong game/paddle.js, ping-pong game/readme.md, ping-pong game/script.js, ping-pong game/styles.css
<hr>
You will play a ping-pong game with the computer. The background color keeps changing which gives a beauty to the game
Fixes #250 
<hr>
<hr>
<hr>
<hr>
=> added ping-pong game

Tribute Page/Assets/css/style.css, Tribute Page/page.html, Tribute Page/readme.md
<hr>
Added a basic web development project. Tribute page project is dedicated to Dr. A. P. J. Abdul Kalam and depicts a trajectory of his life. 
Fixes #320 
<hr>
<hr>
<hr>
<hr>
https://user-images.githubusercontent.com/80174214/158395211-49193c26-541f-43dc-88f6-39753ae0ccbc.mp4
=> Added Tribute Page

38.IP-Address Tracker/Readme.md, 38.IP-Address Tracker/design.css, 38.IP-Address Tracker/index.html
I have fixed issue #293 Kindly Review this.
<hr>
Fixes #293 
<hr>
Please delete options that are not relevant. And in order to tick the check box just but x inside them for example [x] like this
- [ x] Add a new project
<hr>
- [x ] Project using HTML, CSS & JS
<hr>
- [x ] I have performed a self-review of my own code or work.
- [ x] I'm GSSoC'22 contributor
<hr>
=> IP Tracker added

Background Generator/README.md, Background Generator/index.html, Background Generator/script.js, Background Generator/style.css, CSS Grid/Grid cheatsheet.txt, CSS Grid/index.html, CSS Grid/style.css
<hr>
Added a new project: Background Generator
Fixes #286 
<hr>
-Add a new project
<hr>
- [Project using HTML, CSS & JS
<hr>
<hr>
=> Added Background generator project

Survey Form/Assets/css/index.css, Survey Form/index.html, Survey Form/readme.md, Survey Form/script/index.js
<hr>
A simple beginner level Survey Form Project 
Fixes #325 
<hr>
<hr>
<hr>
<hr>
=> Added Survey Form Project

CSS Grid/Grid cheatsheet.txt, CSS Grid/README.md, CSS Grid/index.html, CSS Grid/style.css
<hr>
This is the CSS Grid Project that I have added
Fixes #284
<hr>
- Add a new project
<hr>
- Project using only HTML & CSS
-  I have performed a self-review of my own code or work.
-I'm GSSoC'22 contributor
<hr>
=> Added CSS Grid project

Catch_Me_If_You_Can/README.md, Catch_Me_If_You_Can/index.html, Catch_Me_If_You_Can/script.js, Catch_Me_If_You_Can/style.css
<hr>
I have added a Catch me if you can game
Fixes [#104](https://github.com/khushi-purwar/WebDev-ProjectKart/issues/104)
<hr>
<hr>
<hr>
<hr>
=> Catch Me If You Can game

Amazon_prime_video_login_page_clone/README.md, Amazon_prime_video_login_page_clone/index.css, Amazon_prime_video_login_page_clone/index.html
<hr>
Added Amazon Prime Video Page clone
Fixes #281 
<hr>
<hr>
<hr>
<hr>
=> Added amazon prime video  page clone

README.md
<hr>
Added labels ,
Added Table of content ,
Added ( back to top - button ) and ( bottom - button ) links ,
Added a table for Projects which are available in this repo. .
All things categorize it, In a systematic way ......
Added Tech-Stack used ,
Added Feedback ,
Added Report Bug link,
Added Request Project link
Fixed :  #269
<hr>
<hr>
<hr>
<hr>
https://github.com/ayush-sleeping/WebDev-ProjectKart/blob/master/README.md
=> Updated : Readme

Spinning Wheel Game/README.md, Spinning Wheel Game/index.html, Spinning Wheel Game/script.js, Spinning Wheel Game/style.css
<hr>
Added Spinning Wheel Game which will give a lucky number from 1 to 10 in each spin.
Fixes #314 
<hr>
<hr>
<hr>
<hr>
=> Added spinning wheel game

Timeline/README.md, Timeline/index.html, Timeline/style.css
<hr>
Timeline made using HTML and CSS
Fixes #285 
<hr>
<hr>
<hr>
=> Added Timeline

Shopping List/README.md, Shopping List/index.html, Shopping List/script.js, Shopping List/style.css
<hr>
This is a basic todo shopping list where we can add our list using DOM events.
Fixes #369 
<hr>
- Add a new project
<hr>
- Project using HTML, CSS & JS
<hr>
<hr>
=> Added Todo Shopping List

Shopping List/index.html, Shopping List/script.js, Shopping List/style.css
<hr>
This is a project that I made using ReactJs. In this project we can sort the robots name according to the typed value in searchbox.
Fixes #370 
<hr>
- Add a new project
<hr>
- Project using ReactJs
<hr>
<hr>
=> Added Robofriends project 

Unit Conversion/README.md, Unit Conversion/calculation.js, Unit Conversion/display.js, Unit Conversion/index.html, Unit Conversion/style.css
<hr>
Added new feature: unit converter.
Using this one can convert length, area, temperature, volume, mass, speed, time, data.
Fixes #318
<hr>
<hr>
<hr>
<hr>
=> Final Commit

39.Reaction tester/README.md, 39.Reaction tester/jsrc.js, 39.Reaction tester/reaction tester.html
<hr>
Reaction Tester Game which is a simple game to check in how many seconds you click on shape of different color that appears on the screen
issue #178 is fixed adding source code
Fixes #178 
<hr>
enhancement  (By adding a new minor game project of level 2)
<hr>
<hr>
<hr>
=> first commit

Technical Documentation Page/README.md, Technical Documentation Page/index.css, Technical Documentation Page/index.html
<hr>
Added a sample Technical Documentation Page on JavaScript aimed at beginners who are into learning responsive web design as well as technical documentation. 
Fixes #386 
<hr>
<hr>
<hr>
<hr>
https://user-images.githubusercontent.com/80174214/160284989-be5674a3-9907-4d53-8279-b32e600bc428.mp4
=> Added Technical Documentation Page on JavaScript

Sample Portfolio Page/README.md, Sample Portfolio Page/index.html, Sample Portfolio Page/style.css
<hr>
Sample Portfolio Website which is beginner-friendly and built using HTML and CSS
Fixes #394 
<hr>
<hr>
<hr>
<hr>
https://user-images.githubusercontent.com/80174214/160655031-b2bd7f5c-c7ba-42f4-b266-dca314a18bec.mp4
=> Sample Portfolio Page

Live User Filter/README.md, Live User Filter/index.html, Live User Filter/script.js, Live User Filter/style.css
Fixed  #427 
here's how it looks -
=> Live user filter

Mobile-Number-Validator/README.md, Mobile-Number-Validator/script.js, Mobile-Number-Validator/style.css, Mobile-Number-Validator/validator.html, README.md
<hr>
Checks whether mobile number is valid or not.
Fixes #432 
<hr>
<hr>
<hr>
<hr>
=> Mobile Number Validator Added

Expense_Tracker/REAMDE.md, Expense_Tracker/index.html, Expense_Tracker/style.css, Expense_Tracker/work.js
<hr>
Added a Expense Tracker built using html cs and js.
Fixes #467 
<hr>
<hr>
<hr>
<hr>
=> Added expense Tracker

Breakout Game/assets/style.css, Breakout Game/index.html, Breakout Game/readme.md, Breakout Game/script/index.js
<hr>
2D Breakout Game using HTML, CSS and JavaScript
Fixes #465
<hr>
<hr>
<hr>
<hr>
=> Breakout Game

Balloon-Popper/README.md, Balloon-Popper/app.js, Balloon-Popper/index.html, Balloon-Popper/style.css
<hr>
A site for popping balloons.
Fixes #477 
<hr>
<hr>
<hr>
<hr>
=> Balloon popper added

Motivational-Quote-Generator/index.html, Motivational-Quote-Generator/readme.md, Motivational-Quote-Generator/script.js, Motivational-Quote-Generator/style1.css, Motivational-Quote-Generator/style2.css
<hr>
In this project, I've created an app that displays random famous quotes each time a button is clicked. The user can display a quote from a famous athlete, politician, or historical figure.
Fixes #474
<hr>
<hr>
<hr>
<hr>
=> Motivational quote generator, Resolving issue #474

Speech Recognition/index.html, Speech Recognition/readme.md, Speech Recognition/script.js, Speech Recognition/style.css
<hr>
It's a Speech Recognition site which will take permission from user to acess the microphone , and whatever user will say that will be written into a different Div Section .
Fixes: #486 
<hr>
<hr>
<hr>
<hr>
https://user-images.githubusercontent.com/77873383/161963527-6238c96f-537e-4e34-88c6-0073dbb74736.mp4
=>  Speech Recognition Website 

Brick-breaker-game/README.md, Brick-breaker-game/index.html, Brick-breaker-game/script.js, Brick-breaker-game/style.css
<hr>
Brick Breaker Geme. Use arrows keys to play.
Fixes #495 
<hr>
<hr>
<hr>
<hr>
=> Brick breaker added

Expanding-Cards/README.md, Expanding-Cards/index.html, Expanding-Cards/script.js, Expanding-Cards/style.css
<hr>
Click on the bars to view expanding cards.
Fixes #508 
<hr>
<hr>
<hr>
<hr>
=> Expanding cards added

Insect-Catch-Game/README.md, Insect-Catch-Game/index.html, Insect-Catch-Game/script.js, Insect-Catch-Game/style.css
<hr>
Play a game of catching insects.
Fixes #510 
<hr>
<hr>
<hr>
<hr>
=> Insect Catch Game added

Hangman-Puzzle/README.md, Hangman-Puzzle/index.html, Hangman-Puzzle/scripts/app.js, Hangman-Puzzle/scripts/hangman.js, Hangman-Puzzle/scripts/request.js, Hangman-Puzzle/styles/style.css
<hr>
Hangman Puzzle - Guess the correct sentence.
Fixes #497 
<hr>
<hr>
<hr>
<hr>
=> Hangman Puzzle Added

Casino Slot Machine Game/index.html, Casino Slot Machine Game/readme.md, Casino Slot Machine Game/script.js, Casino Slot Machine Game/style.css
<hr>
Slot machines include one or more currency detectors that validate the form of payment, whether coin, cash, voucher, or token. The machine pays out according to the pattern of symbols displayed when the reels stop "spinning".
Fixes: #488 
<hr>
<hr>
<hr>
<hr>
=> Casino Slot Machine Game

SnakeGame_SpeechRecognition/index.html, SnakeGame_SpeechRecognition/main.js, SnakeGame_SpeechRecognition/readme.md, SnakeGame_SpeechRecognition/speechCommand.js, SnakeGame_SpeechRecognition/style.css
Fixes #514 
https://imgur.com/a/VKvJ21b
https://imgur.com/a/MElkQB3
=> Snake game using speech recognition in javascript

Color Generator/design.css, Color Generator/index.html, Color Generator/readme.md, Color Generator/script.js
<hr>
I have created a web app to generate random colors based on JS, that comes with a handful of options.
Fixes #460
<hr>
<hr>
<hr>
<hr>
[![Click on this banner](https://user-images.githubusercontent.com/82095877/162185056-79e8a007-c63e-4b2b-a77e-7d07489d2831.png)](https://youtu.be/Wj07_SUXrqc)
=> Random color Generator based on HexaDecimal System

Text-To-Speech-Convertor/README.md, Text-To-Speech-Convertor/index.html, Text-To-Speech-Convertor/script.js, Text-To-Speech-Convertor/style.css
<hr>
This is a simple JavaScript project that converts the entered text into the speech 
Fixes #216 
<hr>
<hr>
<hr>
<hr>
=> Text-To-Speech Convertor Added

Keeper/Readme.md, Keeper/package.json, Keeper/public/index.html, Keeper/public/styles.css, Keeper/src/components/App.jsx, Keeper/src/components/CreateArea.jsx, Keeper/src/components/Footer.jsx, Keeper/src/components/Header.jsx, Keeper/src/components/Note.jsx, Keeper/src/index.js
<hr>
Added Keeper ReactApp.
Fixes #524 
<hr>
<hr>
<hr>
<hr>
=> Added Keeper ReactAPP

.vscode/settings.json, Neumophormic Login Form/README.md, Neumophormic Login Form/index.html, Neumophormic Login Form/style.css
<hr>
Neumophormic Login Form Ui
Fixes #587 
<hr>
<hr>
<hr>
<hr>
=> Added Neumophormic Login Form

Form Wave/README.md, Form Wave/index.html, Form Wave/script.js, Form Wave/style.css
<hr>
A html form with wave effect. click on the text area to see the effect.
Fixes #548 
<hr>
<hr>
<hr>
<hr>
=> Form Wave Project Added

Blurry-Loading-Project/README.md, Blurry-Loading-Project/index.html, Blurry-Loading-Project/script.js, Blurry-Loading-Project/style.css
<hr>
Blurry Landing Page with help of HTML,CSS,JS.
Fixes #547 
<hr>
<hr>
<hr>
<hr>
=> Blurry Landing Project added

Colorful_Rain_Effect/.vscode/settings.json, Dad-Jokes/README.md, Dad-Jokes/index.html, Dad-Jokes/script.js, Dad-Jokes/style.css
<hr>
A joke site that is fetched from api.
Fixes #568 
<hr>
<hr>
<hr>
<hr>
=> Dad Jokes  Project added

Rotating-Animation-Navigation/README.md, Rotating-Animation-Navigation/index.html, Rotating-Animation-Navigation/script.js, Rotating-Animation-Navigation/style.css
<hr>
Rotates the whole of the landing page on one click.
Fixes #549 
<hr>
<hr>
<hr>
<hr>
=> Rotated Animation Navigation Added

Random-password-generator/README.md, Random-password-generator/index.css, Random-password-generator/index.html, Random-password-generator/index.js
<hr>
A Program that generates up to 4 random passwords of length 6.
Fixes #582 
<hr>
<hr>
<hr>
<hr>
https://user-images.githubusercontent.com/92387745/162494664-c671c5ae-5d3f-4108-a8dd-2840b85d7034.mp4
=> Random-password generator program added

Game of Rock Paper Scissors/README.md, Game of Rock Paper Scissors/index.html, Game of Rock Paper Scissors/script.js, Game of Rock Paper Scissors/styles.css
<hr>
A DOM-based rock paper scissors JavaScript Game, that aims to take you through the nostalgia.
Fixes #535
<hr>
<hr>
<hr>
<hr>
=> Rock Paper Scissors Game

Scroll-Animation-Page/README.md, Scroll-Animation-Page/index.html, Scroll-Animation-Page/script.js, Scroll-Animation-Page/style.css
<hr>
Amazing scroll animation with help of HTML,CSS,JS.
Fixes #566 
<hr>
<hr>
<hr>
<hr>
=> Scroll Animation Page added

Wordle_Clone/README.md, Wordle_Clone/index.html, Wordle_Clone/script.js, Wordle_Clone/style.css
<hr>
This is a simple clone of the most popular web-based word game called "Wordle" built using HTML , CSS and JavaScript.
Fixes #607 
<hr>
<hr>
<hr>
<hr>
=> Added wordle clone

Ludo Game Board Design/index.html, Ludo Game Board Design/readme.md, Ludo Game Board Design/style.css
<hr>
Added Ludo Game Board Design
Fixes #585 
<hr>
<hr>
<hr>
<hr>
=> Added Ludo Game Board Design

Incrementing Counter/README.md, Incrementing Counter/index.html, Incrementing Counter/script.js, Incrementing Counter/style.css
<hr>
An increasing counter that ends at some value. 
Fixes #620 
<hr>
<hr>
<hr>
<hr>
=> Incrementing Counter Added

Particle js animation/README.md, Particle js animation/app.js, Particle js animation/index.html, Particle js animation/particles.js
<hr>
webpage with particle js animation.
Fixes #452 
<hr>
<hr>
<hr>
<hr>
=> particles js animation

QR Code Scanner/Assets/css/index.css, QR Code Scanner/README.md, QR Code Scanner/index.html, QR Code Scanner/scripts/index.js
<hr>
- Added QR Code Scanner
- Added corresponding README
Fixes #652 
<hr>
<hr>
<hr>
<hr>
https://user-images.githubusercontent.com/80174214/162606709-f41d025e-ee74-425c-b61c-c44969fa5f7d.mp4
=> Added QR Code Scanner

Microsoft Clone/README.md, Microsoft Clone/app.js, Microsoft Clone/index.html, Microsoft Clone/style.css
<hr>
A clone of microsoft homepage.
Fixes #631 
<hr>
<hr>
<hr>
<hr>
=> Microsoft Clone added

CSS Bicycle/README.md, CSS Bicycle/index.html, CSS Bicycle/style.css
<hr>
An awesome moving bicycle animation with the help of HTML and CSS. 
Fixes #473
<hr>
<hr>
<hr>
<hr>
=> CSS Bicycle

Math Sprint Game/README.md, Math Sprint Game/index.html, Math Sprint Game/main.js, Math Sprint Game/shuffle.js
<hr>
This game checks your IQ speed, how fast you can calculate maths solutions with different rounds
- 1st round 10 questions
- 2nd round 25 questions
- 3rd round 50 questions
- 4th round 99 questions
Fixes #698 
<hr>
<hr>
<hr>
<hr>
=> Added Math Sprint Game

Random Choice Picker/README.md, Random Choice Picker/index.html, Random Choice Picker/script.js, Random Choice Picker/style.css
<hr>
Picks a choice out of random choices for you.
Fixes #618 
<hr>
<hr>
<hr>
<hr>
=> Random Choice Picker added

Event KeyCodes/README.md, Event KeyCodes/index.html, Event KeyCodes/script.js, Event KeyCodes/style.css
<hr>
It tells the code of any pressed key.
Fixes #617 
<hr>
<hr>
<hr>
<hr>
=> Event Key Codes added

Video Player/README.md, Video Player/index.html, Video Player/script.js, Video Player/style.css
<hr>
It will works as a normal video player had different speeds of 2x.5x zoom in window volume controller
Fixes #639 
<hr>
<hr>
<hr>
<hr>
https://user-images.githubusercontent.com/73753957/162593173-166d0aa2-478f-4364-8a82-2531b87df62b.mp4
=> Added Video Player

HTML5 Canvas Animation/README.md, HTML5 Canvas Animation/index.html, HTML5 Canvas Animation/index.js, HTML5 Canvas Animation/style.css
<hr>
HTML5 Canvas Animation added using HTML5 Canvas API
Fixes #621
<hr>
<hr>
<hr>
<hr>
=> HTML5 Canvas Animation added

Spotify Clone/index.html, Spotify Clone/readme.md, Spotify Clone/script.js, Spotify Clone/style.css
<hr>
Making a clone of a well-known music player spotify.
Fixes #580 
<hr>
<hr>
<hr>
<hr>
=> Spotify Clone

Toggle Dark - Light Mode/README.md, Toggle Dark - Light Mode/index.html, Toggle Dark - Light Mode/style.css
<hr>
This is a simple website for toggling between light and dark mode with beautiful designing , colors , transitions , and animations. 
Fixes #742 
<hr>
<hr>
<hr>
<hr>
=> Dark-Light mode toggle

Joke teller/README.md, Joke teller/index.html, Joke teller/main.js, Joke teller/style.css, Joke teller/style.less
<hr>
It is a simple website that tells a joke by speaking.
Fixes #795 
<hr>
<hr>
<hr>
<hr>
=> Added Joke teller 

Speed Typer/Readme.md, Speed Typer/index.html, Speed Typer/script.js, Speed Typer/style.css
<hr>
Speed Typer is an efficient application to increase your typing speed. All you have to do is typer sum random words that pop on screen with in seconds of time
Fixes #733 
<hr>
<hr>
<hr>
<hr>
=> Added Speed Typer

Loruki Landing Page/Readme.md, Loruki Landing Page/index.html, Loruki Landing Page/style.css, Loruki Landing Page/utilities.css
<hr>
Loruki is a Cloud hosting website for everyone. Here you can deploy your favorite apps, within a seconds
Fixes #767 
<hr>
<hr>
<hr>
<hr>
=> Added Cloud Deployment Landing Page

Matrix Transpose Calculator/index.html, Matrix Transpose Calculator/readme.md, Matrix Transpose Calculator/script.js, Matrix Transpose Calculator/style.css
<hr>
A web-app-based fully responsive Transpose Matrix Calculator to solve your math problems.
Fixes #701 
<hr>
<hr>
<hr>
<hr>
=>  Transpose matrix calculator

Number System Converter/index.html, Number System Converter/readme.md, Number System Converter/script.js, Number System Converter/style.css
<hr>
A web app-based fully responsive Number System converter.
Fixes #700 
<hr>
<hr>
<hr>
<hr>
=> Number System Converter

Bill Splitter/edit.css, Bill Splitter/index.html, Bill Splitter/work.js
<hr>
WE have to enter the total bill amount and the number of persons amongst whom we have to split the bill, and accordingly it will be displayed who has to pay how much, and with proper UI/UX.
Fixes #793 
<hr>
<hr>
<hr>
<hr>
https://lhdsplit2.netlify.app/
=> Bill Splitter

Generate Random Names/index.html, Generate Random Names/readme.md, Generate Random Names/script.js, Generate Random Names/style.css
<hr>
Added a Random Name Generator website which will be create everytime You click on generate button.
Fixes #786 
<hr>
<hr>
<hr>
<hr>
https://user-images.githubusercontent.com/77873383/163334099-57dc4ea0-325c-4313-9cbe-6c11b742af4a.mp4
=> Generate Random Name

.docs/PULL_REQUEST_TEMPLATE.md, .github/ISSUE_TEMPLATE/add-project.md, .github/PULL_REQUEST_TEMPLATE.md
<hr>
Template updated
Fixes #890 
<hr>
=> Template updated

Bookmark Saver/README.md, Bookmark Saver/index.html, Bookmark Saver/script.js, Bookmark Saver/style.css
<hr>
It saves your favorite site as a bookmark
Fixes #887 
<hr>
<hr>
<hr>
<hr>
=> Bookmark Saver

Scramble Game/index.html, Scramble Game/script.js, Scramble Game/style.css
<hr>
Added Scramble Game
Fixes #507
<hr>
<hr>
<hr>
<hr>
=> Added Scramble Game

Hotel-Booking-App/package.json, Hotel-Booking-App/public/index.html, Hotel-Booking-App/readme.md, Hotel-Booking-App/src/App.js, Hotel-Booking-App/src/Filters/Filter.js, Hotel-Booking-App/src/Filters/index.js, Hotel-Booking-App/src/Hotels/BestsellerFlag.js, Hotel-Booking-App/src/Hotels/Hotel.js, Hotel-Booking-App/src/Hotels/Perk.js, Hotel-Booking-App/src/Hotels/RoomsLeft.js, Hotel-Booking-App/src/Hotels/index.js, Hotel-Booking-App/src/data.js, Hotel-Booking-App/src/index.js, Hotel-Booking-App/src/styles.css, Memory Card Game/Readme.md
A fully responsive web app for hotel booking.
Fixes #898 
<hr>
<hr>
<hr>
=> adding hotel booking app

Name Plate Generator/app.js, Name Plate Generator/index.html, Name Plate Generator/readme.md, Name Plate Generator/style.css
<hr>
A web app to generate a name plate for you.
Fixes #901 
<hr>
<hr>
<hr>
<hr>
=> adding name plate generator

Income Tax Calculator/index.html, Income Tax Calculator/readme.md, Income Tax Calculator/script.js, Income Tax Calculator/style.css
<hr>
It's a Income Tax Calculator, made using HTML,CSS,JS . Here user have to put annual salary and calculated tax will be displayed in another Div Section.
---
Fixes #856 
<hr>
<hr>
<hr>
<hr>
=> Income Tax Calculator

Long Drive/README.md, Long Drive/index.html, Long Drive/style.css
<hr>
A moving car animation made using HTML and CSS.
Fixes #799 
<hr>
<hr>
<hr>
<hr>
=> Long Drive

Falling_Ball_Game/index.html, Falling_Ball_Game/script.js, Falling_Ball_Game/style.css, Temperature-Converter-Website/README.md, Temperature-Converter-Website/index.html, Temperature-Converter-Website/script.js, Temperature-Converter-Website/style.css
<hr>
Fixes #672
<hr>
<hr>
<hr>
<hr>
[
](url)
=> Temperature Convereter Website

adblock detector/README.md.md, adblock detector/index.html, adblock detector/main.js, adblock detector/style.css
<hr>
Adblock detector for detecting the Adblockers in a browser
Fixes #832 
<hr>
<hr>
<hr>
- [] My changes generates no new warnings.
<hr>
=> feat:adblock detector added

Magic Ball 8/index.html, Magic Ball 8/readme.md, Magic Ball 8/script.js, Magic Ball 8/style.css
<hr>
JavaScript code so that you can grab the 8 ball, ask it a question, shake it, and have the 8 ball respond with a somewhat enigmatic, somewhat applicable answer.
Fixes #963 
<hr>
<hr>
<hr>
<hr>
https://user-images.githubusercontent.com/82095877/165143943-b7868845-8b35-4ef3-9757-11aad8b2a474.mp4
=> adding magic ball 8 game

Calculate EMI🧮/index.html, Calculate EMI🧮/readme.md, Calculate EMI🧮/script.js, Calculate EMI🧮/style.css
<hr>
It's a EMI calculator which is made using HTML,CSS,JS . Here are 3 options -->
- Loan Amount
- interest rate/year
- Duration
These 3 will be taken from users.
And all the output will be shown into different Div consisting -> 
- Monthly Installment 
- Monthly Interest
- Total Repayment 
- Total Interest Cost
Fixes #926 
<hr>
<hr>
<hr>
<hr>
https://user-images.githubusercontent.com/77873383/164891388-74ac890e-2275-4f1f-9a51-d951eab22198.mp4
=> Calculate EMI🧮

Epic Playlist/css/normalize.css, Epic Playlist/css/styles.css, Epic Playlist/index.html, Epic Playlist/readme.md, Epic Playlist/script.js
<hr>
A web app-based playlist 
Fixes #987 
<hr>
<hr>
<hr>
<hr>
https://user-images.githubusercontent.com/82095877/165346417-23b91750-b497-464b-a91e-535a0f9b752e.mp4
=> adding epic playlist

thumbnail downloader/README.md.md, thumbnail downloader/css/css.css, thumbnail downloader/index.html, thumbnail downloader/js/js.js
<hr>
youtube thumbnail downloader, let's user download any videos thumbnail.
Fixes #1005
<hr>
<hr>
<hr>
- [] My changes generates no new warnings.
<hr>
##Screenshots …
=> feat: thumbnail downloader added

Discussion Portal/index.html, Discussion Portal/index.js, Discussion Portal/readm, Discussion Portal/readme.md
<hr>
It is a discussion portal where one user can add questions and the other user can respond to those questions. Also once the query is resolved, the user can delete the added question and response.
Fixes #1019 
<hr>
<hr>
<hr>
<hr>
=> Discussion Portal

Type_Writer/Assets/css/style.css, Type_Writer/README.md, Type_Writer/index.html, Type_Writer/script/index.js
<hr>
Fixes #1049
<hr>
<hr>
<hr>
<hr>
=> type writer added

Pomodoro Clock/index.html, Pomodoro Clock/readme.md, Pomodoro Clock/script.js, Pomodoro Clock/style.css
<hr>
A web app based pomodoro clock.
Fixes #<issue_number_here>
<hr>
<hr>
<hr>
<hr>
https://user-images.githubusercontent.com/82095877/166001735-a0968279-ade8-46db-a955-7697a1915662.mp4
=> Pomodoro Clock

Tic-Tac-Toe/index.html, Tic-Tac-Toe/script.js, Tic-Tac-Toe/style.css
<hr>
Fixes #1075
<hr>
<hr>
<hr>
- [] My changes generates no new warnings.
- [] I'm GSSoC'22 …
=> Tic Tac Game

Password Validation/Readme, Password Validation/index.html, Password Validation/script.js, Password Validation/style.css
<hr>
The idea behind this project
Just trying to login into any Github and every time I got a msg as your password is not matching, the message was not exactly the same but it tried to convey the same. This was the process of validation. So, I decided to build the same.
How does it work
While loading this project you will have two inputs enter your password and the second one is to reenter your password for matching if your entry data will the same in both fields then while submitting you will get a pop of confirmation as matched otherwise warning message.
If your Input field will be in empty condition then you have an alert msg
Fixes #1092 
<hr>
<hr>
Please …
=> Password Validation

Random Advice generator/Readme, Random Advice generator/index.html, Random Advice generator/script.js
<hr>
Like in javascript we have many projects such as random quote generators and password generators and many more so I took the basic idea from there only.
You just need to load the file in the browser you will have an interface as a container containing a message of Click the refresh and below three is refresh button by doing so, as it API project then it will request data from the server after fetching it you will have random advice in your container.
Fixes #1095
<hr>
<hr>
<hr>
Please delete options that are not relevant. And in …
=> Random Advice Generator

wall breaker/ball.js, wall breaker/brick.js, wall breaker/index.html, wall breaker/paddle.js
<hr>
Fixes #<issue_number_here>
#1115 
<hr>
<hr>
<hr>
<hr>
=> wall breaker

Weight Converter/index.html, Weight Converter/readme.md, Weight Converter/script.js, Weight Converter/style.css
<hr>
The user will enter the weight in grams which will be converted into grams, pounds and ounces and stones.
Fixes <#1120>
<hr>
<hr>
<hr>
<hr>
=> Weight Converter

github-profiles/index.html, github-profiles/scripts/init.js, github-profiles/scripts/main.js, github-profiles/styles/styles.css
Hey I made github profile Project Which Is Very Good!
=> adding github profile

Vowel Counter/Index.html, Vowel Counter/Readme.md, Vowel Counter/script.js, Vowel Counter/style.css
<hr>
How can get numbers of vowels from a list of paragraphs?
while loading the project we will have a text box where we can enter text and below the text box we have a submit button by clicking on the submit button you will be able to see how many vowels are available in the random text.
**Stack**:  
And in order to tick the check box just put x inside them for example - [x] like this. Please delete options that are not relevant.
Fixes #1122 
<hr>
<hr>
<hr>
Please delete options that are not relevant. And in order to tick the check …
=> Vowel counter

recipe-finder/index.html, recipe-finder/readme.md, recipe-finder/script.js, recipe-finder/style.css
<hr>
recipe finder  is a JavaScript app which will help you find many recipes and will suggest you random recipes.
Fixes #1166
<hr>
<hr>
<hr>
- [] My changes generates no new warnings.
<hr> …
=> feat: recipe finder added

Take A Screenshot/index.html, Take A Screenshot/readme.md, Take A Screenshot/script.js, Take A Screenshot/style.css
<hr>
It's a Screenshot Taking Application made using **HTML,CSS,JS** where User have to paste a website Link of which he/she wants to take screenshot and the application create a Screenshot of that link
- Fixes #1164 
<hr>
<hr>
<hr>
<hr>
https://user-images.githubusercontent.com/77873383/166617387-e15706a0-9ca1-40cf-9ccf-57a1ecd74355.mp4
=> Take A Screenshot🎥

drawing-app/index.html, drawing-app/script.js, drawing-app/style.css
Hey I made drawing app Project Which Is Very Good!
=> Adding drawing app

relaxer-app/README.md.md, relaxer-app/app.js, relaxer-app/med.html, relaxer-app/style.css
<hr>
relaxation app is an app which will help you out with breathing
Fixes #1038
<hr>
<hr>
<hr>
- [] My changes generate no new warnings.
<hr> …
=> feat: relaxation app added

Portfolio template 2/index.css, Portfolio template 2/index.html, Portfolio template 2/index.js
<hr>
Portfolio website with transitions
user interactive ui
responsive
will use this template in real time project where user can find desired and cool templates free to use for their portfolio website
Fixes #<issue_number_here>
#1221 
<hr>
<hr>
<hr>
- [] I have commented on …
=> portfolio template 2.0

Alarm App/app.js, Alarm App/index.html, Alarm App/readme.md, Alarm App/style.css
<hr>
To make an alarm app using html,css and javascript
Fixes #1202 
<hr>
<hr>
<hr>
<hr>
=> Issue #1202 resolved: Alarm App

Character counter/Readme.md, Character counter/index.html, Character counter/script.js, Character counter/style.css
<hr>
It is the basic idea of forgetting how many characters have in any pdf or word file.
while loading the project we will have a text box where we can enter text and below at the right corner there will be a live character count that will preview how many characters are there.
Fixes #1246 
<hr>
<hr>
<hr>
<hr>
https://user-images.githubusercontent.com/73521123/167016318-df433ea4-3f6a-47e9-bb3d-795850bf4128.mp …
=> Character counter

Country-tour/Readme.md, Country-tour/index.html, Country-tour/script.js, Country-tour/style.css
<hr>
Is any way to access the details of the country like their population and currency
while loading the project we will have a text box where we can enter the country name and beside the text box we have a submit button by clicking on the submit button you will be able to see your search country details.
whenever we login into any web page then there in the login form they set up the auto validation functionality with the help of javascript.  This means each part of the form has restricted if is an email section then there should be a valid email otherwise it wouldn't accept.
While loading there will be a registration form for you just need to enter the data as per the required field and at the end hit the submit button. So, from here javascript will validate each filed value if there …
=> Country-tour

Google Photos Clone/README.md, Google Photos Clone/package.json, Google Photos Clone/public/index.html, Google Photos Clone/public/manifest.json, Google Photos Clone/public/robots.txt, Google Photos Clone/src/App.js, Google Photos Clone/src/actions/index.js, Google Photos Clone/src/api/album.js, Google Photos Clone/src/api/photo.js, Google Photos Clone/src/components/Album.js, Google Photos Clone/src/components/CreateAlbumModal.js, Google Photos Clone/src/components/Login.js, Google Photos Clone/src/components/Nav.js, Google Photos Clone/src/components/Photo.js, Google Photos Clone/src/css/App.css, Google Photos Clone/src/css/HomePage.css, Google Photos Clone/src/css/Nav.css, Google Photos Clone/src/css/Photo.css, Google Photos Clone/src/css/index.css, Google Photos Clone/src/firebase.example.js, Google Photos Clone/src/index.js, Google Photos Clone/src/pages/AlbumPage.js, Google Photos Clone/src/pages/HomePage.js, Google Photos Clone/src/reducers/albumReducer.js, Google Photos Clone/src/reducers/index.js, Google Photos Clone/src/reducers/userReducer.js, Google Photos Clone/src/store.js
<hr>
Google photos clone with React Js
Fixes #1277 
<hr>
<hr>
<hr>
<hr>
https://user-images.githubusercontent.com/73753957/167170028-a7dac70c-d521-4c1c-bbae-490fdba97437.mp4
=> Google Photos Clone

Car Racing Game/index.html, Car Racing Game/read, Car Racing Game/readme.md
<hr>
A fully responsive web app for Car Racing Game.
Fixes #1282 
<hr>
<hr>
<hr>
<hr>
https://user-images.githubusercontent.com/82095877/167179305-f9ce7fbe-53ae-44a9-93cf-8b85c8a6334c.mp4
=> Car Racing Game

Mortgage Calculator/index.html, Mortgage Calculator/loancalculator.css, Mortgage Calculator/loancalculator.js, Mortgage Calculator/readme.md
<hr>
A fully responsive mortgage calculator
Fixes #1141 
<hr>
<hr>
<hr>
<hr>
https://user-images.githubusercontent.com/82095877/167180369-8588d154-6cf4-41e5-b844-c2753a5497fb.mp4
=> Mortgage Calculator

Number Guessing Game/README.md, Number Guessing Game/index.html, Number Guessing Game/script.js, Number Guessing Game/style.css
Worked ON Issue Number: #1269 
Issue Name: Add Number Guessing Game.
Issue Type: Feature Request.
Added Video in README.md
=> Number guessing game

Background Generator/README.md
<hr>
- Added Readme File into pre-exisiting project [background-generator](https://github.com/khushi-purwar/WebDev-ProjectKart/tree/master/Background%20Generator)
- Fixes #1294 
<hr>
<hr>
<hr>
https://user-images.githubusercontent.com/77873383/167236157-a764951e-1132-4907-b71e-6aea4b702087.mp4
=> Added Readme into 'Background generator"

Grocery store/readme.md
<hr>
- Added Readme File into pre-exisiting project **Grocery Store**
- Fixes #1305
<hr>
<hr>
<hr>
<hr>
=> added Grocery Store readme

Maze Runner/.gitignore, Maze Runner/index.html, Maze Runner/mazerunner.js, Maze Runner/style.css, Maze Runner/survival.html, Maze Runner/template.js
<hr>
Fixes #<issue_number_here>
#1319 
<hr>
<hr>
<hr>
<hr>
=> Maze Runner

SlingShot/README.md, SlingShot/game.js, SlingShot/index.html, SlingShot/matter.js, SlingShot/styles.css
Worked ON Issue Number: #1299 
Issue Name: SlingShot Game
Issue Type: Feature Adding.
Video:
https://user-images.githubusercontent.com/77090462/167243753-00443906-296d-4ebc-9782-8111809b08eb.mov
=> Sling shot

Random-Meal-Generator/README.md, Random-Meal-Generator/index.html, Random-Meal-Generator/script.js, Random-Meal-Generator/style.css
Worked On Issue Number: #1300 
Issue Name: Random Meal Generator.
Issue Type: Feature Added.
Video:
https://user-images.githubusercontent.com/77090462/167242777-fd64f441-b9c8-41eb-9864-7223bce1ee60.mov
=> Random meal

Emoji Generator (Searcher)/README.md, Emoji Generator (Searcher)/app.js, Emoji Generator (Searcher)/index.css, Emoji Generator (Searcher)/index.html
<hr>
Emoji Searcher with a search box to search for any emoji required. The matching results are then dynamically rendered on the screen. 
Link to the JSON file used: https://raw.githubusercontent.com/github/gemoji/master/db/emoji.json
Fixes #789 
<hr>
<hr>
<hr>
<hr>
https://user-images.githubusercontent.com/80174214/167248766-04094b3f-52a6-45a8-b81b-a812901c048c.mp4
=> Emoji Searcher or Generator

Binary_Calculator/index.css, Binary_Calculator/index.html, Binary_Calculator/index.js
<hr>
Added Binary calculator that performs 4 operation on binary numbers
Fixes #1191 
<hr>
<hr>
<hr>
<hr>
https://user-images.githubusercontent.com/82600388/167246670-67a6f80e-dcc1-4818-a277-510a9388b4e9.mp4
=> Added Binary calculator

DOM object manipulator/index.html, DOM object manipulator/script.js, DOM object manipulator/style.css
<hr>
DOM Object Manipulator  show the power of javascript in an interesting and interactive manner ....make cool different objects . enjoy!
Fixes #1261 
<hr>
<hr>
<hr>
<hr>
=> DOM Object Manipulator 

speech command listener/index.html, speech command listener/script.js, speech command listener/style.css, speech command listener/values.json
<hr>
this application takes your commands and questions as input and gives the answer as output .  You just have to ask!.....cool right :)
Fixes #1336 
<hr>
<hr>
<hr>
<hr>
=> Speech Command Listener 

Email Extractor/index.html, Email Extractor/readme.md
<hr>
A fully responsive web app based Email Extractor
Fixes #1306 
<hr>
<hr>
<hr>
<hr>
https://user-images.githubusercontent.com/82095877/167263879-22a14236-3efe-4eb2-86e6-552620edaa56.mp4
=> Email Extractor

Rocket Animation/index.html, Rocket Animation/script.js, Rocket Animation/style.css
<hr>
Fixes #1370
<hr>
<hr>
<hr>
<hr>
=> Rocket Animation

Add to Cart/index.html, Add to Cart/script.js, Add to Cart/style.css
<hr>
Fixes #1355 
<hr>
<hr>
<hr>
<hr>
=> Add to cart

index.html, style.css
<hr>
Improved Main website UI and linked all the projects
Fixes #1333 
<hr>
<hr>
<hr>
=> Main website UI and added all projects

Unsplash Clone/README.md, Unsplash Clone/package.json, Unsplash Clone/public/index.html, Unsplash Clone/public/manifest.json, Unsplash Clone/src/App.js, Unsplash Clone/src/components/Categories.js, Unsplash Clone/src/components/Header.js, Unsplash Clone/src/components/Hero.js, Unsplash Clone/src/components/Image.js, Unsplash Clone/src/css/App.css, Unsplash Clone/src/css/Catergories.css, Unsplash Clone/src/css/Header.css, Unsplash Clone/src/css/Hero.css, Unsplash Clone/src/css/Image.css, Unsplash Clone/src/css/ImageGrid.css, Unsplash Clone/src/css/index.css, Unsplash Clone/src/index.js, Unsplash Clone/src/pages/HomePage.js, Unsplash Clone/src/pages/SearchPage.js, Unsplash Clone/src/unsplash.js
<hr>
Unsplash Clone with React JS
Fixes #1382 
<hr>
<hr>
<hr>
<hr>
https://user-images.githubusercontent.com/73753957/167263615-77a5670f-c961-4162-8d4c-efb9bcfcf7d7.mp4
=> Unsplash Clone

Restuarant Landing Page/README.md, Restuarant Landing Page/index.html, Restuarant Landing Page/style.css
<hr>
It's a UI of the Restaurant Page
Fixes #1471 
<hr>
<hr>
<hr>
<hr>
=> Restaurant Landing Page

Face detection using JS/README.md.md, Face detection using JS/face.html, Face detection using JS/face.js, Face detection using JS/styles.css
<hr>
Real Time Face Detector using JavaScript
Fixes #1295
<hr>
<hr>
<hr>
- [] My changes generate no new warnings.
<hr>
https://user-images.githubusercontent.com/84259582/167308509-5d17a54b-be2b-4783-8c …
=> feat: Face Detector added

world_map/data.json, world_map/index.html, world_map/index.js
*Fixed #1347
<hr>
This website show us map of the world. It also has feature of zoom effect to view small cities and town.
Fixes #1347 
<hr>
<hr>
<hr>
<hr>
=> Added world map

Pure CSS Background Fruit/index.html, Pure CSS Background Fruit/style.css
<hr>
Fixes #1423  
<hr>
<hr>
<hr>
<hr>
=> CSS Background

Advance mp3 Player/script.js
<hr>
Fixes #1468 
I made rightmost play/pause button work as expected, before that only play feature was working , when you click for pause ,it restart the song again and again, which was not desired output. 
<hr>
<hr>
<hr>
<hr>
=> player-bug-fixed

Apple Website Clone/index.html, Apple Website Clone/style/style.css
<hr>
Fixes #1467
Footer content was not present as Apple website , Now I added each and every footer component present in actual Apple website , so that it look like today's apple website. I build entire Footer.
<hr>
<hr>
<hr>
- [] My changes generate no new warnings.
- [] I'm GSSoC'22 …
=> footer-contents-added

Plan The Day/package.json, Plan The Day/public/index.html, Plan The Day/readme.md, Plan The Day/src/App.js, Plan The Day/src/App.test.js, Plan The Day/src/Plan.js, Plan The Day/src/index.css, Plan The Day/src/index.js, Plan The Day/src/reportWebVitals.js, Plan The Day/src/setupTests.js
<hr>
- **Plan Your Day**
- Fixes #1291 
<hr>
<hr>
<hr>
<hr>
https://user-images.githubusercontent.com/77873383/167341569-0173ecd6-7e54-4bd3-8853-82f05f43f822.mp4
=> Plan Your Day using ReactJS

Ball animation/index.html, Ball animation/style.css
Hey I made ball animation Project Which Is Very Good!
=> adding ball animation

Random wave/index.html, Random wave/script.js, Random wave/style.css
Hey I made random wave Project Which Is Very Good!
=> Adding random wave

Flappy Bird 2.0/index.html, Flappy Bird 2.0/readme.md
<hr>
A fully responsive web app for flappy bird game
Fixes #1450 
<hr>
<hr>
<hr>
<hr>
https://user-images.githubusercontent.com/82095877/167421164-977265e0-f64d-49e4-a39d-07f81ac2bfaf.mp4
=> Flappy Bird

GK FlipBook/README.md, GK FlipBook/index.html, GK FlipBook/pics.json, GK FlipBook/script.js, GK FlipBook/style.css
<hr>
General knowledge digital flipbook ...happy learning:)
Fixes #1427 
<hr>
<hr>
<hr>
<hr>
https://user-images.githubusercontent.com/91609324/167297209-aa2e202b-7705-428e-992c-720c2e4b9b2b.mp4
[README (2).md](https://github.com/khushi-purwar/WebDev-ProjectKart/files/8651733/README.2.md)
=> GK FlipBook files added

Multi-functioned Notes App/Readme.md, Multi-functioned Notes App/index.css, Multi-functioned Notes App/index.html, Multi-functioned Notes App/index.js
<hr>
Responsive Multifunctionality Notes app
Fixes #1436 
<hr>
<hr>
<hr>
<hr>
https://user-images.githubusercontent.com/82600388/167369948-540c4227-faf0-41c7-879a-6793eb2b2b7e.mp4
=> Added Responsive Multi-functionality notes app

Missile Game/README.md, Missile Game/asteroid.js, Missile Game/asteroid.svg, Missile Game/background.svg, Missile Game/index.html, Missile Game/main.js, Missile Game/ship.js, Missile Game/ship.svg
Worked on Issue Number: #1404 
Issue Name: Missile Game
Issue Type: Feature Added
https://user-images.githubusercontent.com/77090462/167466389-131930b5-e96b-4606-8e2f-3d95d10824f3.mov
=> Missile game

WhiteBoard/index.html, WhiteBoard/script.js, WhiteBoard/style.css
<hr>
Fixes #1497 
<hr>
<hr>
<hr>
<hr>
=> Whiteboard

Drink Water App/index.html, Drink Water App/readme.md, Drink Water App/script.js, Drink Water App/style.css
<hr>
It's a Daily water Tracker Application using HTML,CSS,JAVASCRIPT
- Fixes #1561
<hr>
<hr>
<hr>
<hr>
https://user-images.githubusercontent.com/77873383/167528627-26548656-ba3a-492c-8d67-67c8af3c8c24.mp4
=> Drink Water Application 🥤🌊

Weather Teller with API/Readme.md, Weather Teller with API/weather_t.css, Weather Teller with API/weather_t.html, Weather Teller with API/weather_t.js
<hr>
Fixes #1437 
<hr>
<hr>
<hr>
<hr>
https://user-images.githubusercontent.com/82600388/167609133-17b1497b-ccdf-4c81-baa4-be528a97a088.mp4
=> Weather teller app with API

Video to Audio Converter/README.md, Video to Audio Converter/index.html, Video to Audio Converter/script.js, Video to Audio Converter/styles.css
<hr>
Video to Audio Converter added
Fixes #1599
<hr>
<hr>
<hr>
<hr>
=> Video to Audio Converter added

CSS Animation Loaders/README.md, CSS Animation Loaders/index.html, CSS Animation Loaders/style.css
<hr>
CSS Animation loaders files added
Fixes #1584 
<hr>
<hr>
<hr>
<hr>
https://user-images.githubusercontent.com/91609324/167593133-c9580ac7-4830-44f1-9b2f-cdfc8ac1ccd1.mp4
=> CSS Animation loaders 

Image Background Modifier/README.md, Image Background Modifier/index.html, Image Background Modifier/script.js, Image Background Modifier/styles.css
<hr>
Image Background Modifier added
Fixes #1637
<hr>
<hr>
<hr>
<hr>
=> Image Background Modifier added

Addition Animation/index.html, Addition Animation/readme.md, Addition Animation/script.js, Addition Animation/style.css
<hr>
Fixes #1693 
<hr>
<hr>
<hr>
<hr>
=> Addition Animation

RGB To Hex And vice versa/Readme.md, RGB To Hex And vice versa/index.html, RGB To Hex And vice versa/script.js, RGB To Hex And vice versa/style.css
<hr>
**Project title**
RGB To HEX Converter.
**Project Description**
We all know this is one of the most ingredients of our web development journey, That is nothing but our color and we already know that we have to assign color values in two different types. That is hex-color and RGB color formate.
In this project, just this is the conversion between them hex color to RGB color. Although we can use any of them while working on a project but just for fun playing I have designed this project.
Fixes #1611   
<hr>
<hr>
<hr>
Please delete …
=> RGB to HEX and vice versa

Dynamic Calender/README.md, Dynamic Calender/index.html, Dynamic Calender/script.js, Dynamic Calender/style.css
Hey I made dynamic calender Project Which Is Very Good!
=> Adding dynamic calender

Emoji-rating/README.md, Emoji-rating/index.html, Emoji-rating/index.js, Emoji-rating/style.css
Hey I made emoji rating Project Which Is Very Good!
=> Addign emoji rating

Profile-statistics/README.md, Profile-statistics/index.html, Profile-statistics/index.js, Profile-statistics/style.css
Hey I made Profile statistic Project Which Is Very Good!
=> Adding Profile statistic

Tab_Navigation/README.md, Tab_Navigation/index.html, Tab_Navigation/script.js, Tab_Navigation/style.css
<hr>
Tab based navigation. On clicking different tabs, you are taken to different sections of the website.
Project link available in README
Fixes #1169 
<hr>
<hr>
<hr>
<hr>
=> Added tab-based navigation

User Data Filter/README.md, User Data Filter/index.html, User Data Filter/script.js, User Data Filter/style.css
<hr>
User Data Filter fetches data from API and user can filter the names from the list.
*took reference and idea from youtube videos
Fixes #1636 
<hr>
<hr>
<hr>
<hr>
https://user-images.githubusercontent.com/91609324/168332033-df0aa7a1-c401-4eb4-a3be-50544db3ac57.mp4
=> User Data Filter 

Random Probability Maker/README.md, Random Probability Maker/index.html, Random Probability Maker/script.js, Random Probability Maker/style.css
<hr>
Random Probability maker  files added with readme
Fixes #1635
also closed pr #1707 because of error ...and started this instead 
<hr>
<hr>
<hr>
<hr>
VIDEO IN README
=> Random Probability maker 

mousemove effect/i.html
<hr>
Fixes #1663 
<hr>
<hr>
<hr>
<hr>
=> mouseMove-effects
